#!/usr/bin/env python
# -*- coding: utf-8 -*-
# pylint: disable=W0613, C0116
# type: ignore[union-attr]
# This program is dedicated to the public domain under the CC0 license.

"""
Basic example for a bot that uses inline keyboards.
"""
import logging
import collections

from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update
from telegram.ext import Updater, CommandHandler, CallbackQueryHandler, CallbackContext

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO
)
logger = logging.getLogger(__name__)


def start(update: Update, context: CallbackContext) -> None:
    keyboard = []
    data = {"Nick": "Wicisian", "Jogger": "11952.1", "Collector": "88725", "Backpaker": "77186", "TotalXP": "76015166" }
    vdata = {"Nick": True, "Jogger": True, "Collector": True, "Backpaker": True, "TotalXP": True}
    context.user_data["ocr_user"] = collections.OrderedDict(data)
    context.user_data["ocr_user_valid"] = collections.OrderedDict(vdata)

    txt = 'Please check the following values:'
    for i in context.user_data["ocr_user"]:
        if context.user_data["ocr_user"][i] is not None:
            value = str(i) + ": " + str(context.user_data["ocr_user"][i]) + " ✅"
            cb_data = list(context.user_data["ocr_user"].keys()).index(i)

            keyboard.append([InlineKeyboardButton(str(value), callback_data=cb_data)])

    keyboard.append([InlineKeyboardButton("Finish", callback_data='finish')])

    """
    keyboard = [
        [
            InlineKeyboardButton("Option1 ✅", callback_data='1'),
            #InlineKeyboardButton("✅", callback_data='Option2')
        ],
        [
            InlineKeyboardButton("Option2 ❌", callback_data='2'),
            #InlineKeyboardButton("❌", callback_data='Option4')
        ],
        [
            InlineKeyboardButton("Option3 ❌", callback_data='3'),
            #InlineKeyboardButton("❌", callback_data='Option6')
        ],
        [InlineKeyboardButton("Terminar", callback_data='0')],
    ]"""

    reply_markup = InlineKeyboardMarkup(keyboard)

    update.message.reply_text('Please choose:', reply_markup=reply_markup)




def help_command(update, context) -> None:
    update.message.reply_text("Use /start to test this bot.")

def button(update, context) -> None:
    query = update.callback_query

    ocr_user_valid = context.user_data["ocr_user_valid"]
    ocr_user = context.user_data["ocr_user"]
    # CallbackQueries need to be answered, even if no notification to the user is needed
    # Some clients may have trouble otherwise. See https://core.telegram.org/bots/api#callbackquery
    query.answer()

    data = query.data
    if data.isnumeric():
        keyboard = query.message.reply_markup['inline_keyboard']
        print(keyboard[int(data)][0]['text'])
        index = list(ocr_user_valid.keys())[int(data)]
        ocr_user_valid[index] = not ocr_user_valid[index]

        if ocr_user_valid[index]:
            keyboard[int(data)][0]['text'] = str(index) + ": " + str(ocr_user[index]) + " ✅"
        else:
            keyboard[int(data)][0]['text'] = str(index) + ": " + str(ocr_user[index]) + " ❌"

        print(keyboard[int(data)][0]['text'])

    else:
        pass


    query.message.reply_text(str(query.data))
    print(query.message.reply_markup)
    #query.edit_message_text(text=f"Selected option: {query.data}")

def main():
    # Create the Updater and pass it your bot's token.
    # Make sure to set use_context=True to use the new context based callbacks
    # Post version 12 this will no longer be necessary
    updater = Updater("1161816070:AAH03yJ7nyZs5r-M5CtZV2XMiF78YXDYsjk", use_context=True)

    updater.dispatcher.add_handler(CommandHandler('start', start))
    updater.dispatcher.add_handler(CallbackQueryHandler(button))
    updater.dispatcher.add_handler(CommandHandler('help', help_command))


    # Start the Bot
    updater.start_polling()

    # Run the bot until the user presses Ctrl-C or the process receives SIGINT,
    # SIGTERM or SIGABRT
    updater.idle()


if __name__ == '__main__':
    main()